MarocLivraison/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace MarocLivraison.Controllers
{
    public class AdminController : Controller
    {
        private readonly IConfiguration configuration;

        public AdminController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public IActionResult Index()
        {
            Console.WriteLine(HttpContext.User);
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return Redirect("/Clients/");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Index(string username, string password, string ReturnUrl)
        {
            var credentials = configuration.GetSection("Auth");

            if (username == credentials["AdminLogin"] && password == credentials["AdminPassword"])
            {
                var claims = new List<Claim>
                 {
                    new Claim(ClaimTypes.Name, username)
                 };

                var claimsIdentity = new ClaimsIdentity(claims, "Login");
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new
                ClaimsPrincipal(claimsIdentity));
                return Redirect(ReturnUrl == null ? "/Clients/" : ReturnUrl);
            }

            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return Redirect("/Admin");
        }
    }
}

MarocLivraison/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarocLivraison.Data;
using MarocLivraison.Models;
using Microsoft.AspNetCore.Authorization;

namespace MarocLivraison.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        private readonly DataContext _context;

        public ClientsController(DataContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientID,RaisonSociale,NomResponsable")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientID,RaisonSociale,NomResponsable")] Client client)
        {
            if (id != client.ClientID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.ClientID == id);
        }
    }
}

MarocLivraison/Controllers/TourneesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarocLivraison.Data;
using MarocLivraison.Models;
using Microsoft.AspNetCore.Authorization;

namespace MarocLivraison.Controllers
{
    [Authorize]
    public class TourneesController : Controller
    {
        private readonly DataContext _context;

        public TourneesController(DataContext context)
        {
            _context = context;
        }

        // GET: Tournees
        public async Task<IActionResult> Index()
        {
            var dataContext = _context.Tournees.Include(t => t.Chauffeur).Include(t => t.Client).Include(t => t.Vehicule);
            return View(await dataContext.ToListAsync());
        }

        // GET: Tournees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournees = await _context.Tournees
                .Include(t => t.Chauffeur)
                .Include(t => t.Client)
                .Include(t => t.Vehicule)
                .FirstOrDefaultAsync(m => m.TourneesID == id);
            if (tournees == null)
            {
                return NotFound();
            }

            return View(tournees);
        }

        // GET: Tournees/Create
        public IActionResult Create()
        {
            ViewData["ChauffeurID"] = new SelectList(_context.Chauffeurs, "ChauffeurID", "CIN");
            ViewData["ClientID"] = new SelectList(_context.Clients, "ClientID", "NomResponsable");
            ViewData["VehiculeID"] = new SelectList(_context.Vehicules, "VehiculeID", "Marque");
            return View();
        }

        // POST: Tournees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TourneesID,ChauffeurID,VehiculeID,ClientID,DateLivraison,Kilometrage,NiveauCarburant,AdresseLivraison,DureeLivraison")] Tournees tournees)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tournees);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChauffeurID"] = new SelectList(_context.Chauffeurs, "ChauffeurID", "CIN", tournees.ChauffeurID);
            ViewData["ClientID"] = new SelectList(_context.Clients, "ClientID", "NomResponsable", tournees.ClientID);
            ViewData["VehiculeID"] = new SelectList(_context.Vehicules, "VehiculeID", "Marque", tournees.VehiculeID);
            return View(tournees);
        }

        // GET: Tournees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournees = await _context.Tournees.FindAsync(id);
            if (tournees == null)
            {
                return NotFound();
            }
            ViewData["ChauffeurID"] = new SelectList(_context.Chauffeurs, "ChauffeurID", "CIN", tournees.ChauffeurID);
            ViewData["ClientID"] = new SelectList(_context.Clients, "ClientID", "NomResponsable", tournees.ClientID);
            ViewData["VehiculeID"] = new SelectList(_context.Vehicules, "VehiculeID", "Marque", tournees.VehiculeID);
            return View(tournees);
        }

        // POST: Tournees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TourneesID,ChauffeurID,VehiculeID,ClientID,DateLivraison,Kilometrage,NiveauCarburant,AdresseLivraison,DureeLivraison")] Tournees tournees)
        {
            if (id != tournees.TourneesID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tournees);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TourneesExists(tournees.TourneesID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ChauffeurID"] = new SelectList(_context.Chauffeurs, "ChauffeurID", "CIN", tournees.ChauffeurID);
            ViewData["ClientID"] = new SelectList(_context.Clients, "ClientID", "NomResponsable", tournees.ClientID);
            ViewData["VehiculeID"] = new SelectList(_context.Vehicules, "VehiculeID", "Marque", tournees.VehiculeID);
            return View(tournees);
        }

        // GET: Tournees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournees = await _context.Tournees
                .Include(t => t.Chauffeur)
                .Include(t => t.Client)
                .Include(t => t.Vehicule)
                .FirstOrDefaultAsync(m => m.TourneesID == id);
            if (tournees == null)
            {
                return NotFound();
            }

            return View(tournees);
        }

        // POST: Tournees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tournees = await _context.Tournees.FindAsync(id);
            _context.Tournees.Remove(tournees);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TourneesExists(int id)
        {
            return _context.Tournees.Any(e => e.TourneesID == id);
        }
    }
}

MarocLivraison/Controllers/VehiculesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MarocLivraison.Data;
using MarocLivraison.Models;
using Microsoft.AspNetCore.Authorization;

namespace MarocLivraison.Controllers
{
    [Authorize]
    public class VehiculesController : Controller
    {
        private readonly DataContext _context;

        public VehiculesController(DataContext context)
        {
            _context = context;
        }

        // GET: Vehicules
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vehicules.ToListAsync());
        }

        // GET: Vehicules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _context.Vehicules
                .FirstOrDefaultAsync(m => m.VehiculeID == id);
            if (vehicule == null)
            {
                return NotFound();
            }

            return View(vehicule);
        }

        // GET: Vehicules/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehicules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VehiculeID,NumImmatriculation,Marque,Modele,DateMiseEnCirculation,Kilometrage")] Vehicule vehicule)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vehicule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehicule);
        }

        // GET: Vehicules/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _context.Vehicules.FindAsync(id);
            if (vehicule == null)
            {
                return NotFound();
            }
            return View(vehicule);
        }

        // POST: Vehicules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VehiculeID,NumImmatriculation,Marque,Modele,DateMiseEnCirculation,Kilometrage")] Vehicule vehicule)
        {
            if (id != vehicule.VehiculeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiculeExists(vehicule.VehiculeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicule);
        }

        // GET: Vehicules/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _context.Vehicules
                .FirstOrDefaultAsync(m => m.VehiculeID == id);
            if (vehicule == null)
            {
                return NotFound();
            }

            return View(vehicule);
        }

        // POST: Vehicules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicule = await _context.Vehicules.FindAsync(id);
            _context.Vehicules.Remove(vehicule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehiculeExists(int id)
        {
            return _context.Vehicules.Any(e => e.VehiculeID == id);
        }
    }
}

MarocLivraison/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarocLivraison</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (Context.User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Clients" asp-action="Index">MarocLivraison</a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">MarocLivraison</a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if (Context.User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Home</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Home</a>
                            }
                        </li>
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown"> 
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Clients" asp-action="Index">Clients</a>
                                    <a class="dropdown-item" asp-controller="Chauffeurs" asp-action="Index">Chauffeurs</a>
                                    <a class="dropdown-item" asp-controller="Vehicules" asp-action="Index">Vehicules</a>
                                    <a class="dropdown-item" asp-controller="Tournees" asp-action="Index">Tournées</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
                @if (Context.User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Logout">Deconnexion</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MarocLivraison - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>